create table if not exists public.template_versions (
  template_id uuid not null references public.game_templates(id) on delete cascade,
  version integer not null check (version > 0),
  status text not null default 'draft' check (status in ('draft', 'review', 'published', 'superseded', 'archived')),
  release_name text,
  release_notes text,
  theme jsonb not null default '{}'::jsonb,
  route_config jsonb not null default '{}'::jsonb,
  validation_report jsonb not null default '{}'::jsonb,
  created_by text,
  updated_by text,
  published_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  published_at timestamptz,
  primary key (template_id, version)
);

create unique index if not exists template_versions_one_open_draft_idx
  on public.template_versions(template_id)
  where status in ('draft', 'review');

create index if not exists template_versions_status_idx
  on public.template_versions(status, updated_at desc);

create table if not exists public.checkpoint_health (
  checkpoint_id uuid primary key references public.template_checkpoints(id) on delete cascade,
  template_id uuid not null,
  version integer not null,
  status text not null default 'pending'
    check (status in ('not_required', 'pending', 'verified', 'needs_attention', 'blocked')),
  checklist jsonb not null default '{}'::jsonb,
  notes text,
  last_checked_at timestamptz,
  verified_at timestamptz,
  verified_by text,
  updated_at timestamptz not null default now(),
  updated_by text,
  foreign key (template_id, version)
    references public.template_versions(template_id, version)
    on delete cascade
);

create index if not exists checkpoint_health_template_version_idx
  on public.checkpoint_health(template_id, version, status);

create table if not exists public.content_audit_log (
  id bigint generated by default as identity primary key,
  template_id uuid references public.game_templates(id) on delete cascade,
  version integer,
  checkpoint_id uuid references public.template_checkpoints(id) on delete set null,
  actor_email text,
  action text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists content_audit_log_template_idx
  on public.content_audit_log(template_id, created_at desc);

alter table public.template_versions enable row level security;
alter table public.checkpoint_health enable row level security;
alter table public.content_audit_log enable row level security;

revoke all on public.template_versions from anon, authenticated;
revoke all on public.checkpoint_health from anon, authenticated;
revoke all on public.content_audit_log from anon, authenticated;

insert into public.template_versions(
  template_id,
  version,
  status,
  release_name,
  release_notes,
  published_at,
  created_at,
  updated_at
)
select
  id,
  active_version,
  'published',
  'Initial published route',
  'Backfilled from the active production template.',
  now(),
  created_at,
  updated_at
from public.game_templates
on conflict (template_id, version) do nothing;

insert into public.checkpoint_health(
  checkpoint_id,
  template_id,
  version,
  status,
  checklist,
  notes,
  updated_at
)
select
  checkpoint.id,
  checkpoint.template_id,
  checkpoint.version,
  case
    when coalesce((checkpoint.config ->> 'field_verification_required')::boolean, false)
      or coalesce((checkpoint.accessibility ->> 'field_verification_required')::boolean, false)
      then 'pending'
    else 'not_required'
  end,
  '{}'::jsonb,
  case
    when coalesce((checkpoint.config ->> 'field_verification_required')::boolean, false)
      or coalesce((checkpoint.accessibility ->> 'field_verification_required')::boolean, false)
      then 'Requires an on-site verification walk before the next publish.'
    else null
  end,
  now()
from public.template_checkpoints checkpoint
join public.template_versions version_row
  on version_row.template_id = checkpoint.template_id
 and version_row.version = checkpoint.version
on conflict (checkpoint_id) do nothing;

create or replace function public.content_create_draft(
  p_template_id uuid,
  p_actor text
)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_source_version integer;
  v_draft_version integer;
  v_new_version integer;
begin
  select version
    into v_draft_version
  from public.template_versions
  where template_id = p_template_id
    and status in ('draft', 'review')
  order by version desc
  limit 1;

  if v_draft_version is not null then
    return v_draft_version;
  end if;

  select active_version
    into v_source_version
  from public.game_templates
  where id = p_template_id
    and is_active = true
  for update;

  if v_source_version is null then
    raise exception 'Active template was not found';
  end if;

  select greatest(
    coalesce((select max(version) from public.template_versions where template_id = p_template_id), 0),
    coalesce((select max(version) from public.template_checkpoints where template_id = p_template_id), 0)
  ) + 1
  into v_new_version;

  insert into public.template_versions(
    template_id,
    version,
    status,
    release_name,
    release_notes,
    theme,
    route_config,
    created_by,
    updated_by
  )
  select
    p_template_id,
    v_new_version,
    'draft',
    coalesce(release_name, 'Draft ' || v_new_version::text),
    null,
    theme,
    route_config,
    p_actor,
    p_actor
  from public.template_versions
  where template_id = p_template_id
    and version = v_source_version;

  if not found then
    insert into public.template_versions(
      template_id,
      version,
      status,
      release_name,
      created_by,
      updated_by
    ) values (
      p_template_id,
      v_new_version,
      'draft',
      'Draft ' || v_new_version::text,
      p_actor,
      p_actor
    );
  end if;

  insert into public.template_checkpoints(
    template_id,
    version,
    slug,
    sequence_no,
    kind,
    latitude,
    longitude,
    radius_meters,
    accessibility,
    config,
    is_optional,
    is_active
  )
  select
    template_id,
    v_new_version,
    slug,
    sequence_no,
    kind,
    latitude,
    longitude,
    radius_meters,
    accessibility,
    config,
    is_optional,
    is_active
  from public.template_checkpoints
  where template_id = p_template_id
    and version = v_source_version
  order by sequence_no;

  insert into public.checkpoint_health(
    checkpoint_id,
    template_id,
    version,
    status,
    checklist,
    notes,
    updated_by
  )
  select
    checkpoint.id,
    checkpoint.template_id,
    checkpoint.version,
    case
      when coalesce((checkpoint.config ->> 'field_verification_required')::boolean, false)
        or coalesce((checkpoint.accessibility ->> 'field_verification_required')::boolean, false)
        then 'pending'
      else 'not_required'
    end,
    '{}'::jsonb,
    case
      when coalesce((checkpoint.config ->> 'field_verification_required')::boolean, false)
        or coalesce((checkpoint.accessibility ->> 'field_verification_required')::boolean, false)
        then 'Draft cloned from version ' || v_source_version::text || '; verify this station in the field.'
      else null
    end,
    p_actor
  from public.template_checkpoints checkpoint
  where checkpoint.template_id = p_template_id
    and checkpoint.version = v_new_version;

  insert into public.content_audit_log(
    template_id,
    version,
    actor_email,
    action,
    payload
  ) values (
    p_template_id,
    v_new_version,
    p_actor,
    'DRAFT_CREATED',
    jsonb_build_object('sourceVersion', v_source_version)
  );

  return v_new_version;
end;
$$;

create or replace function public.content_publish_version(
  p_template_id uuid,
  p_version integer,
  p_actor text,
  p_allow_unverified boolean default false
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_status text;
  v_checkpoint_count integer;
  v_missing_content integer;
  v_finale_count integer;
  v_finale_not_last integer;
  v_location_missing integer;
  v_unverified integer;
  v_errors jsonb := '[]'::jsonb;
  v_warnings jsonb := '[]'::jsonb;
  v_report jsonb;
begin
  select status
    into v_status
  from public.template_versions
  where template_id = p_template_id
    and version = p_version
  for update;

  if v_status is null then
    raise exception 'Template version was not found';
  end if;

  if v_status not in ('draft', 'review') then
    raise exception 'Only a draft or review version can be published';
  end if;

  select count(*)
    into v_checkpoint_count
  from public.template_checkpoints
  where template_id = p_template_id
    and version = p_version
    and is_active = true;

  select count(*)
    into v_missing_content
  from public.template_checkpoints
  where template_id = p_template_id
    and version = p_version
    and is_active = true
    and (
      coalesce(config #>> '{content,he,title}', '') = ''
      or coalesce(config #>> '{content,en,title}', '') = ''
      or coalesce(config #>> '{content,he,prompt}', '') = ''
      or coalesce(config #>> '{content,en,prompt}', '') = ''
    );

  select count(*)
    into v_finale_count
  from public.template_checkpoints
  where template_id = p_template_id
    and version = p_version
    and is_active = true
    and kind = 'finale'::public.checkpoint_kind;

  select count(*)
    into v_finale_not_last
  from public.template_checkpoints checkpoint
  where checkpoint.template_id = p_template_id
    and checkpoint.version = p_version
    and checkpoint.is_active = true
    and checkpoint.kind = 'finale'::public.checkpoint_kind
    and checkpoint.sequence_no <> (
      select max(sequence_no)
      from public.template_checkpoints
      where template_id = p_template_id
        and version = p_version
        and is_active = true
    );

  select count(*)
    into v_location_missing
  from public.template_checkpoints
  where template_id = p_template_id
    and version = p_version
    and is_active = true
    and (
      kind in ('location'::public.checkpoint_kind, 'finale'::public.checkpoint_kind)
      or coalesce((config ->> 'field_verification_required')::boolean, false)
    )
    and (latitude is null or longitude is null or radius_meters is null or radius_meters <= 0);

  select count(*)
    into v_unverified
  from public.template_checkpoints checkpoint
  left join public.checkpoint_health health
    on health.checkpoint_id = checkpoint.id
  where checkpoint.template_id = p_template_id
    and checkpoint.version = p_version
    and checkpoint.is_active = true
    and (
      coalesce((checkpoint.config ->> 'field_verification_required')::boolean, false)
      or coalesce((checkpoint.accessibility ->> 'field_verification_required')::boolean, false)
    )
    and coalesce(health.status, 'pending') <> 'verified';

  if v_checkpoint_count = 0 then
    v_errors := v_errors || jsonb_build_array(jsonb_build_object(
      'code', 'no_checkpoints',
      'message', 'The route must contain at least one active checkpoint.'
    ));
  end if;

  if v_missing_content > 0 then
    v_errors := v_errors || jsonb_build_array(jsonb_build_object(
      'code', 'missing_bilingual_content',
      'message', v_missing_content::text || ' checkpoint(s) are missing Hebrew or English title/prompt.'
    ));
  end if;

  if v_finale_count <> 1 then
    v_errors := v_errors || jsonb_build_array(jsonb_build_object(
      'code', 'invalid_finale_count',
      'message', 'The route must contain exactly one finale.'
    ));
  end if;

  if v_finale_not_last > 0 then
    v_errors := v_errors || jsonb_build_array(jsonb_build_object(
      'code', 'finale_not_last',
      'message', 'The finale must be the last active checkpoint.'
    ));
  end if;

  if v_location_missing > 0 then
    v_errors := v_errors || jsonb_build_array(jsonb_build_object(
      'code', 'missing_location',
      'message', v_location_missing::text || ' location-sensitive checkpoint(s) are missing coordinates or radius.'
    ));
  end if;

  if v_unverified > 0 then
    v_warnings := v_warnings || jsonb_build_array(jsonb_build_object(
      'code', 'field_verification_required',
      'message', v_unverified::text || ' checkpoint(s) still require field verification.'
    ));
  end if;

  v_report := jsonb_build_object(
    'ok', jsonb_array_length(v_errors) = 0 and (p_allow_unverified or v_unverified = 0),
    'errors', v_errors,
    'warnings', v_warnings,
    'checkpointCount', v_checkpoint_count,
    'unverifiedCount', v_unverified,
    'generatedAt', now()
  );

  update public.template_versions
  set validation_report = v_report,
      updated_at = now(),
      updated_by = p_actor
  where template_id = p_template_id
    and version = p_version;

  if jsonb_array_length(v_errors) > 0 or (v_unverified > 0 and not p_allow_unverified) then
    return v_report;
  end if;

  update public.template_versions
  set status = 'superseded',
      updated_at = now(),
      updated_by = p_actor
  where template_id = p_template_id
    and status = 'published'
    and version <> p_version;

  update public.template_versions
  set status = 'published',
      published_at = now(),
      published_by = p_actor,
      updated_at = now(),
      updated_by = p_actor
  where template_id = p_template_id
    and version = p_version;

  update public.game_templates
  set active_version = p_version,
      updated_at = now()
  where id = p_template_id;

  insert into public.content_audit_log(
    template_id,
    version,
    actor_email,
    action,
    payload
  ) values (
    p_template_id,
    p_version,
    p_actor,
    'VERSION_PUBLISHED',
    jsonb_build_object('allowUnverified', p_allow_unverified, 'report', v_report)
  );

  return v_report;
end;
$$;

revoke all on function public.content_create_draft(uuid, text) from public, anon, authenticated;
revoke all on function public.content_publish_version(uuid, integer, text, boolean) from public, anon, authenticated;
grant execute on function public.content_create_draft(uuid, text) to service_role;
grant execute on function public.content_publish_version(uuid, integer, text, boolean) to service_role;
